// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CitySelect: typeof import('./components/city-select/city-select.vue')['default']
    LabelInput: typeof import('./components/labelInput.vue')['default']
    LiuyunoTabs: typeof import('./components/liuyuno-tabs/liuyuno-tabs.vue')['default']
    PullList: typeof import('./components/pullList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./components/upload/upload.vue')['default']
    ZhangyuQrcodePoster: typeof import('./components/zhangyu-qrcode-poster/zhangyu-qrcode-poster.vue')['default']
  }
}
